### Python

In [1]:
print("Hello World")

Hello World


In [2]:
Print("Hello World") #it should be written as print not Print

NameError: name 'Print' is not defined

In [ ]:
print(Hello World) #strings should be defined wih inverted commas

In [ ]:
!python --version #python version

In [ ]:
5*7+8

In [ ]:
34/2

In [ ]:
a=5
b=8
c=a+b

In [ ]:
c #we wrote c again to get the output

In [ ]:
a=5
b=6
c=a+b
d=a-b
c
d

In [ ]:
#we only got output for the last one i.e. d

In [ ]:
c,d #to get multipe outputs

In [ ]:
a,b,c=20,40,'hi'

In [ ]:
a,b,c

In [ ]:
a=b=c='test'
b

In [ ]:
a

In [ ]:
c

### Data Types

In [ ]:
#Variables

In [ ]:
name='Rishabh'

In [ ]:
1name='Rishabh' #variable name should not start with a number but can have number at any other place

In [ ]:
_name='Rishabh' #only underscore can be used at the start as a variable name and nothing else

In [ ]:
n1ame='rishabh' #variable name should not start with a number but can have number at any other place

In [ ]:
#Data Types are of 5 types

In [ ]:
a='latha' #string
type(a)

In [ ]:
b=3 #integer
type(b)

In [ ]:
c=3.6 #float
type(c)

In [ ]:
d=2j #complex
type(d)

In [ ]:
x='True'# inside ' ' True/False is considered as string
type(x)

In [ ]:
x=True #boolean
type(x)

### Data Structure

In [ ]:
x = ("apple","banana","cherry")
type(x)

In [ ]:
x = ["apple","banana","cherry"]
type(x)

In [ ]:
x = {"name" : "John", "Age" : 22}
type(x)

In [ ]:
x = {"apple","banana","cherry"}
type(x)

### List

In [ ]:
# allows heterogenous
# index starts from 0
# mutable using index
# [     ]

In [ ]:
sample_list=[12,43,56,"hi",1+2j]
sample_list

In [ ]:
type(sample_list)

In [ ]:
sample_list[4]

In [ ]:
sample_list[20]

In [ ]:
sample_list[1]

In [ ]:
sample_list[2]

In [ ]:
sample_list[2] = 3.5

In [ ]:
sample_list

In [ ]:
sample_list.reverse()

In [ ]:
sample_list

In [ ]:
sample_list[1]=100


In [ ]:
sample_list[0]=500

In [ ]:
sample_list.sort()

In [ ]:
sample_list

### Tuple

In [ ]:
# Allows heterogenous
# index starts from 0 and retrieve using index
# cannot change the data once declared - immutable
# (     ) or without it

In [ ]:
sample_tuple=(1,56,3.5,"hi",1+2j)
sample_tuple

In [ ]:
sample_tuple=1,56,3.5,"hi",1+2j
sample_tuple

In [ ]:
type(sample_tuple)

In [ ]:
sample_tuple[0]

In [ ]:
sample_tuple[2]

In [ ]:
sample_tuple[7]

In [ ]:
sample_tuple.reverse()

In [ ]:
sample_tuple[0]=13 #immutable

In [ ]:
sample_tuple.append(1)

In [ ]:
sample_tuple.remove(1)

### SET

In [ ]:
#add hetegogenous
#does not allow duplicates
#cannot access using index
#immutable usig index
#mutable using elements
#ordered-first place ""

In [ ]:
sample_set={1,2,3,4,5,32,45,1,0,2,3,4,25,63,57,235,25,"hi","hello","abc",253}
type(sample_set)

In [ ]:
sample_set 

In [ ]:
sample_set[2]

In [ ]:
sample_set.remove(1)
sample_set

In [ ]:
sample_set.add(999)
sample_set

In [ ]:
sample_set.pop()    ##randomly picks an element

In [ ]:
sample_set.update([22,33,44,55,888]) #to add multiple elements at once
sample_set

### Dictionary

### Important points
It has key value pair data structure /n
Key is unique and values can be duplicate
can retrieve the value using key
can change the value using key
key is immutable


In [ ]:
#It has key value pair data structure /n
#Key is unique and values can be duplicate
#can retrieve the value using key
#can change the value using key
#key is immutable

In [5]:
sample_dict = {"a":"alpha",1:"first",2:"second",3:"third",4:"fourth",5:"fifth",6:"sixth"}
sample_dict

{'a': 'alpha',
 1: 'first',
 2: 'second',
 3: 'third',
 4: 'fourth',
 5: 'fifth',
 6: 'sixth'}

In [6]:
type(sample_dict) #a,1,2,3,4,5,6 are keys and alpha,first,second....are values

dict

In [7]:
sample_dict["a"]

'alpha'

In [8]:
sample_dict[5]="seventh" #mutable using key

In [9]:
sample_dict

{'a': 'alpha',
 1: 'first',
 2: 'second',
 3: 'third',
 4: 'fourth',
 5: 'seventh',
 6: 'sixth'}

In [10]:
sample_dict[5] #retrieve value using key

'seventh'

In [11]:
sample_dict[10]="tenth" #we can add key and values to a dictonary
sample_dict

{'a': 'alpha',
 1: 'first',
 2: 'second',
 3: 'third',
 4: 'fourth',
 5: 'seventh',
 6: 'sixth',
 10: 'tenth'}

In [12]:
sample_dict.reverse()

AttributeError: 'dict' object has no attribute 'reverse'

In [13]:
sample_dict.pop("a")
sample_dict

{1: 'first',
 2: 'second',
 3: 'third',
 4: 'fourth',
 5: 'seventh',
 6: 'sixth',
 10: 'tenth'}

### String
#### string can be retrieved using index
#### string is immutable

In [14]:
a="hi my boy"
type(a)

str

In [15]:
a[0]

'h'

In [16]:
a[5]

' '

In [17]:
a[0]='x' #immutable

TypeError: 'str' object does not support item assignment

## NUMPY: Package for Multidimentional Array
### Vector(1D)
#### Matrix(2D Or 1D)

### Create an array

In [18]:
import numpy as np

In [19]:
simple_list=[6,7,9] #way 1 to create an array
np.array(simple_list)

array([6, 7, 9])

In [20]:
arr=np.array([6, 7, 9]) #way 2 to create an array
arr

array([6, 7, 9])

In [21]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9]) #creating another array
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) #creating another array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(5,28) #strating no is 5 and ending no is 28-1=27, also we have not specified any stepsize

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [26]:
np.arange(5,35,6) #6 is the stepsize

array([ 5, 11, 17, 23, 29])

In [28]:
np.zeros(6) #zeros

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [30]:
np.ones(5) # ones

array([1., 1., 1., 1., 1.])

In [31]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [32]:
np.ones((2,5),dtype=int) # 2 and 5 are rows and columns

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [34]:
np.linspace(0,1,5) 

#starts from 0, last number is 1, 5 is the total no. of output with 4 partitions (equally spaced.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
np.linspace(0,20,10) #1st no-0,last no. - 20, 10 outputs with 9 partitions

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [36]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
np.random.rand(2,4) #uniform distribution b/w 0 and 1

array([[0.99168485, 0.6346421 , 0.51379273, 0.09166035],
       [0.13949974, 0.49587567, 0.96016114, 0.33922016]])

In [41]:
np.random.randn(2,4) #positive as well as negative numbers

array([[ 0.41001372, -1.61103148, -1.93159279,  1.24305961],
       [-1.77268029,  1.23722499,  0.25888184,  0.28265835]])

In [43]:
np.random.rand(2,5) 

array([[0.92983955, 0.46220733, 0.92240661, 0.34701896, 0.83148195],
       [0.61667351, 0.95806973, 0.14873807, 0.16567116, 0.46660648]])

In [44]:
np.random.randint(0,10,100) # from 0 to 9, we would we getting 100 random numbers

array([3, 1, 4, 9, 9, 7, 1, 3, 9, 4, 5, 4, 2, 3, 0, 5, 8, 7, 3, 7, 9, 0,
       8, 0, 4, 8, 2, 2, 2, 9, 2, 9, 3, 6, 3, 4, 3, 6, 2, 9, 9, 8, 7, 0,
       8, 6, 1, 5, 5, 6, 3, 0, 9, 6, 0, 4, 7, 2, 9, 0, 4, 5, 2, 5, 1, 4,
       1, 3, 7, 2, 5, 2, 8, 4, 6, 5, 2, 1, 5, 1, 4, 7, 6, 2, 2, 7, 1, 0,
       1, 7, 6, 8, 3, 6, 7, 7, 0, 2, 3, 7])

In [45]:
np.random.randint(10,100,15) 

array([74, 72, 70, 83, 15, 82, 59, 82, 20, 39, 64, 48, 80, 16, 16])

In [47]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [56]:
rand_array=np.random.randint(0,10,5)
rand_array

array([6, 5, 4, 0, 1])

In [55]:
sample_array.min()

2

In [51]:
sample_array.argmin() #it gives index of min value

0

In [57]:
rand_array.argmin()

3

In [58]:
rand_array.max()

6

In [59]:
sample_array.argmax()

17

In [61]:
sample_array.dtype

dtype('int32')

In [62]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
a=np.random.rand(2,3) #rand ----uniform distribution
a

array([[0.57036521, 0.81370439, 0.80314034],
       [0.04535792, 0.91771374, 0.28527265]])

In [64]:
a.T #Transpose matrix

array([[0.57036521, 0.04535792],
       [0.81370439, 0.91771374],
       [0.80314034, 0.28527265]])

In [66]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [68]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [69]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [70]:
sample_array=sample_array.reshape(3,8)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,8)

In [71]:
sample_array[5]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [72]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [73]:
sample_array[3:9] 

array([13, 14, 15, 16, 17, 18])

In [76]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [77]:
subset_sample_array=sample_array[0:7]
subset_sample_array

In [79]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])